service: default
runtime: go111
#api_version: go1
instance_class: F1

handlers:
- url: /static
  static_dir: app/frontend/static
- url: /api/fr24
  script: auto
  login: admin
- url: /.*
  script: auto
