service: backend
runtime: go
api_version: go1
instance_class: B2
basic_scaling:
  max_instances: 10
  idle_timeout: 4m


handlers:
- url: /static
  static_dir: static
- url: /be/fr24
  script: _go_app
  login: admin
# Find a way to make batch exempt ...
- url: /.*
  script: _go_app
#  login: required
