service: backend
runtime: go111
instance_class: B1
basic_scaling:
  max_instances: 10
  idle_timeout: 4m


handlers:
# strictly speaking, this is redundant; the default app serves /static.
- url: /static
  static_dir: app/backend/static
# Find a way to make batch exempt ...
- url: /.*
  script: auto
#  login: required
